### Docker image build (Renku)
variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "true"
  GIT_LFS_SKIP_SMUDGE: 1
  DOCKER_BUILDKIT: 1

stages:
  - test
  - deploy
  - build

### RenkuLab Docker image build
image_build:
  stage: build
  image: docker:stable
  # only:
  #   changes:
  #     - Dockerfile
  #     - setup.py
  #     - environment.yml
  #     - requirements.txt
  #     - mzbsuite/*
  #     - scripts/*
  #     - workflows/*
  #     - data/*
  #     - configs/*
  #     - models/*
  #     - .gitlab-ci.yml
  #     - .dockerignore
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script: |
    CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 .
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7
    echo -e "\n\n\n The Docker image can be located at: \n" $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 "\n\n\n"