# This file contains the configuration for the Hummingbirds pipeline 
root_folder: /data/shared/hummingbird-classifier
video_folder: /data/shared/raw-data-import/data/raw-hierarchy/
rng_seed: 42

# Data and preprocessing configuration 
video_format: 'mp4' # Video format of the ouput videos
still_frames_location: /data/shared/raw-data-import/data/raw-hierarchy/
target_learning_set_location: /data/shared/hummingbird-classifier
annotations_file: /data/shared/raw-data-import/data/annotations/Interactions_corrected.csv
sampling_rate_negatives: [75, 4, 4] # list of intervals from which to sample negtative frames (trn/val/tst)
current_video_root: /data/shared/raw-video-import/data/
cpu_cores_parallel_jobs: 4

# Fine tuning configuration for Hummingbirds
